HealthNet/healthnet_BKZ/HealthNet/HealthNet/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    # URL for Djangos login solution, also currently the splash page
    url(r'^login', 'django.contrib.auth.views.login', name='login'),
    url(r'^admin/', admin.site.urls),
    url(r'^', include('main.urls')),
    url(r'^', include('fullcalendar.urls', namespace="fullcalendar")),
    url(r'^messages/', include('postman.urls', namespace="postman", app_name='postman'))

]

HealthNet/healthnet_BKZ/HealthNet/main/urls.py
from django.conf.urls import url
from django.conf import settings
from . import views
from log.views import *
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.auth.decorators import login_required


app_name = 'main'

# url's for main application
urlpatterns = [
    # URL for Djangos logout solution, redirects to our own success page after logging them out
    url(r'^logout/$', 'django.contrib.auth.views.logout', {'next_page': '/logout_success/'}),
    # Landing page for logging out users
    url(r'^logout_success/$', views.LogoutSuccess.as_view(), name='logout_success'),
    # URL for the profile page
    url(r'^profile/$', views.profileView, name='profile'),
    # URL for the about page
    url(r'^about/$', login_required(views.AboutView), name='about'),
    # URL for new Home Page
    url(r'^$', views.HomeView.as_view(), name='home'),
    # URL for the contact page
    url(r'^contact/$', login_required(views.ContactView.as_view()), name='contact'),
    # URL for the edit profile page
    url(r'^edit_profile/$', login_required(views.ProfileUpdateView.as_view()), name='edit_profile'),
    # URL for the regrestration page
    url(r'^register/$', views.RegisterView.as_view(), name='register1'),
    # URL for the message doctor page
    url(r'^message/$', login_required(views.MessageView.as_view()), name='message'),
    # URL for the prescriptions page
    url(r'^prescription/(?P<pk>[0-9]+)$', login_required(views.WritePrescriptionView.as_view()), name='prescribe'),
    # URL to access the admin page
    url(r'^adminc/$', AdminView, name='adminc'),
    url(r'^staffregist/$', login_required(StaffRegisterView.as_view()), name='staffregist'),
    url(r'^hospital/(?P<pk>[0-9]+)$', login_required(HospitalStatView.as_view()), name='hospital'),
    # URL for the Test page
    url(r'^test/(?P<pk>[0-9]+)$', login_required(views.TestCreateView.as_view()), name='test'),
    url(r'^editTest/(?P<pk>[0-9]+)$', login_required(views.TestEditView.as_view()), name='editTest'),
    url(r'^deleteTest/(?P<pk>[0-9]+)$', login_required(views.DeleteTest.as_view()),
        name='deleteTest'),
    url(r'^releaseTest/(?P<pk>[0-9]+)$', login_required(views.TestReleaseView.as_view()),
        name='releaseTest'),
    url(r'^deletePrescription/(?P<pk>[0-9]+)$', login_required(views.DeletePrescription.as_view()),
        name='deletePrescription'),
    # URL for the view_patient page
    url(r'^view_patient/(?P<pk>[0-9]+)$', login_required(views.PatientView.as_view()), name='viewPatient'),
    url(r'^discharge_patient/(?P<pk>[0-9]+)$', login_required(views.DischargePatientView.as_view()), name='discharge'),
    url(r'^transfer_patient/(?P<pk>[0-9]+)$', login_required(views.TransferPatientView.as_view()), name='transfer'),
    url(r'^admit_patient/(?P<pk>[0-9]+)$', login_required(views.AdmitPatientView.as_view()), name='admit'),
    #URL for the page the patient list page
    url(r'^patients/$', login_required(views.PatientListView.as_view()), name='patients'),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT,}),
    url(r'confirm_download/$', login_required(views.ConfirmDownloadView.as_view()), name='confirm_download'),
    url(r'confirm_test_download/$', login_required(views.ConfirmTestDownloadView.as_view()), name='confirm_test_download'),
    url(r'download_info/$', login_required(views.DownloadProfileView), name='download'),
    url(r'download_test_info/$', login_required(views.DownloadTestView), name='download_test_info')
]

urlpatterns += staticfiles_urlpatterns()
#urlpatterns += static(settings.MEDIA_URL, document_root=MEDIA_ROOT)

HealthNet/healthnet_BKZ/HealthNet/postman/urls.py
"""
If the default usage of the views suits you, simply use a line like
this one in your root URLconf to set up the default URLs::

    (r'^messages/', include('postman.urls', namespace='postman', app_name='postman')),

Otherwise you may customize the behavior by passing extra parameters.

Recipients Max
--------------
Views supporting the parameter are: ``WriteView``, ``ReplyView``.
Example::
    ...View.as_view(max=3), name='write'),
See also the ``POSTMAN_DISALLOW_MULTIRECIPIENTS`` setting

User filter
-----------
Views supporting a user filter are: ``WriteView``, ``ReplyView``.
Example::
    def my_user_filter(user):
        if user.get_profile().is_absent:
            return "is away"
        return None
    ...
    ...View.as_view(user_filter=my_user_filter), name='write'),

function interface:
In: a User instance
Out: None, False, '', 'a reason', or ValidationError

Exchange filter
---------------
Views supporting an exchange filter are: ``WriteView``, ``ReplyView``.
Example::
    def my_exchange_filter(sender, recipient, recipients_list):
        if recipient.relationships.exists(sender, RelationshipStatus.objects.blocking()):
            return "has blacklisted you"
        return None
    ...
    ...View.as_view(exchange_filter=my_exchange_filter), name='write'),

function interface:
In:
    ``sender``: a User instance
    ``recipient``: a User instance
    ``recipients_list``: the full list of recipients or None
Out: None, False, '', 'a reason', or ValidationError

Auto-complete field
-------------------
Views supporting an auto-complete parameter are: ``WriteView``, ``ReplyView``.
Examples::
    ...View.as_view(autocomplete_channels=(None,'anonymous_ac')), name='write'),
    ...View.as_view(autocomplete_channels='write_ac'), name='write'),
    ...View.as_view(autocomplete_channel='reply_ac'), name='reply'),

Auto moderators
---------------
Views supporting an ``auto-moderators`` parameter are: ``WriteView``, ``ReplyView``.
Example::
    def mod1(message):
        # ...
        return None
    def mod2(message):
        # ...
        return None
    mod2.default_reason = 'mod2 default reason'
    ...
    ...View.as_view(auto_moderators=(mod1, mod2)), name='write'),
    ...View.as_view(auto_moderators=mod1), name='reply'),

function interface:
In: ``message``: a Message instance
Out: rating or (rating, "reason")
    with reting: None, 0 or False, 100 or True, 1..99

Others
------
Refer to documentation.
    ...View.as_view(form_classes=(MyCustomWriteForm, MyCustomAnonymousWriteForm)), name='write'),
    ...View.as_view(form_class=MyCustomFullReplyForm), name='reply'),
    ...View.as_view(form_class=MyCustomQuickReplyForm), name='view'),
    ...View.as_view(template_name='my_custom_view.html'), name='view'),
    ...View.as_view(success_url='postman:inbox'), name='reply'),
    ...View.as_view(formatters=(format_subject, format_body)), name='reply'),
    ...View.as_view(formatters=(format_subject, format_body)), name='view'),

"""
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import url
if getattr(settings, 'POSTMAN_I18N_URLS', False):
    from django.utils.translation import pgettext_lazy
else:
    def pgettext_lazy(c, m): return m
from django.views.generic.base import RedirectView

from .views import (InboxView, SentView, ArchivesView, TrashView,
        WriteView, ReplyView, MessageView, ConversationView,
        ArchiveView, DeleteView, UndeleteView, MarkReadView, MarkUnreadView, BaseView)


urlpatterns = [
    # Translators: keep consistency of the <option> parameter with the translation for 'm'
    url(pgettext_lazy('postman_url', r'^inbox/(?:(?P<option>m)/)?$'), InboxView.as_view(), name='inbox'),
    # Translators: keep consistency of the <option> parameter with the translation for 'm'
    url(pgettext_lazy('postman_url', r'^sent/(?:(?P<option>m)/)?$'), SentView.as_view(), name='sent'),
    # Translators: keep consistency of the <option> parameter with the translation for 'm'
    url(pgettext_lazy('postman_url', r'^archives/(?:(?P<option>m)/)?$'), ArchivesView.as_view(), name='archives'),
    # Translators: keep consistency of the <option> parameter with the translation for 'm'
    url(pgettext_lazy('postman_url', r'^trash/(?:(?P<option>m)/)?$'), TrashView.as_view(), name='trash'),
    url(pgettext_lazy('postman_url', r'^write/(?:(?P<recipients>[^/#]+)/)?$'), WriteView.as_view(), name='write'),
    url(pgettext_lazy('postman_url', r'^reply/(?P<message_id>[\d]+)/$'), ReplyView.as_view(), name='reply'),
    url(pgettext_lazy('postman_url', r'^view/(?P<message_id>[\d]+)/$'), MessageView.as_view(), name='view'),
    # Translators: 't' stands for 'thread'
    url(pgettext_lazy('postman_url', r'^view/t/(?P<thread_id>[\d]+)/$'), ConversationView.as_view(), name='view_conversation'),
    url(pgettext_lazy('postman_url', r'^archive/$'), ArchiveView.as_view(), name='archive'),
    url(pgettext_lazy('postman_url', r'^delete/$'), DeleteView.as_view(), name='delete'),
    url(pgettext_lazy('postman_url', r'^undelete/$'), UndeleteView.as_view(), name='undelete'),
    url(pgettext_lazy('postman_url', r'^mark-read/$'), MarkReadView.as_view(), name='mark-read'),
    url(pgettext_lazy('postman_url', r'^mark-unread/$'), MarkUnreadView.as_view(), name='mark-unread'),
    url(pgettext_lazy('postman_url', r'^'), BaseView.as_view(), name='base'),

]

HealthNet/healthnet_BKZ/HealthNet/postman/templates/postman/base.html
{% extends 'main/base_nav.html' %}
{% load staticfiles %}
{% load main_extras %}
<!DOCTYPE HTML>
<!--
	Minimaxing by HTML5 UP
	html5up.net | @ajlkn
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
  {% block page-title %} Messaging {% endblock %}
  <body>
  {% block main %}
  <div>
      <div id="page-wrapper">
        {% include 'main/navbar.html' %}
        
      </div>

      {# not myself but a site-level one (TEMPLATE_DIRS setting) #}
      {% load i18n static %}{% load postman_tags %}
      {% block title %}<h2> Messaging </h2>{% endblock %}
      {% block extrahead %}

      {% endblock %}
      {% block postman_menu %}
      <div class="container">
          <div class="well">
              <ul id="postman_menu">{% postman_unread as unread_count %}
                  <li><a class="button_temp" href="{% url 'postman:inbox' %}">&raquo;&nbsp;{% trans "Inbox" %}{% if unread_count %} <strong>({{ unread_count }})</strong>{% endif %}</a><br></li>
                  <li><br></li>
                  <li><a class="button_temp" href="{% url 'postman:write' %}">&raquo;&nbsp;{% trans "Write Message" %}</a></li>
                  <li><br></li>
                  <li><a class="button_temp" href="{% url 'postman:sent' %}">&raquo;&nbsp;{% trans "Sent Messages" %}</a></li>
                  <li><br></li>
                  <li><a class="button_temp" href="{% url 'postman:archives' %}">&raquo;&nbsp;{% trans "Archives" %}</a></li>
                  <li><br></li>
                  <li><a class="button_temp" href="{% url 'postman:trash' %}">&raquo;&nbsp;{% trans "Trash" %}</a></li>
              </ul>
          </div>
      </div>
      {% endblock %}

  </div>
  {% endblock %}
  </body>

HealthNet/healthnet_BKZ/HealthNet/postman/templates/postman/base_folder.html
{% extends 'main/base_nav.html' %}
{% load staticfiles %}
{% load main_extras %}
<!DOCTYPE HTML>
<!--
	Minimaxing by HTML5 UP
	html5up.net | @ajlkn
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
<html>
	{% block page-title %} Messaging {% endblock %}

  {% block main %}
  <div>
      <div id="page-wrapper">
          {% include 'main/navbar.html' %}
      </div>


            {% load i18n postman_tags %}{% load pagination_tags %}{% comment %}
            WARNING: 'pagination_tags' is a name from the django-pagination application.
            For convenience, the design of this template is done with the use of that application.
            Django-postman will still be working, even if that application is not installed, by providing a mock
            for the template tag library.
            If the real implementation is to be used, just make sure that 'pagination' is declared before 'postman'
            in the INSTALLED_APPS setting.
            {% endcomment %}
            {% block content %}
            <div id="postman">
                <div class="container">
                    <br>
                    <div class="row">
                        <div class="well">
                            <h2>{% block pm_folder_title %}{% endblock %}</h2>
                            {% autopaginate pm_messages %}
                            {% if invalid_page %}
                            <p>{% trans "Sorry, this page number is invalid." %}</p>
                            {% else %}
                            {% if pm_messages %}
                            {% block pm_by_modes %}

                            <div id="pm_by_modes">
                            <div> Sort box by: </div>
                                <span class="pm_by_mode">
                                    {% if by_message %}
                                        <a href="{{ by_conversation_url }}" style="margin-right:20px">
                                     {% endif %}
                                            {% trans "by conversation" %}
                                     {% if by_message %}
                                        </a>
                                    {% endif %}
                                </span>
                                <span class="pm_by_mode">
                                    {% if by_conversation %}
                                        <a href="{{ by_message_url }}" style="margin-left:20px">
                                    {% endif %}
                                            {% trans "by message" %}
                                    {% if by_conversation %}
                                        </a>
                                    {% endif %}
                                </span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>{% endblock pm_by_modes %}

            <div class="container">
                <div class="row">
                    <div class="well">
                        <form action="{% block pm_form_action %}{% endblock %}" method="post">
                            {% csrf_token %}
                            {% block pm_form_buttons %}<span id="pm_buttons">
                            {% block pm_delete_button %}<button class="button_temp_red pull-right" type="submit" onclick="this.form.action='{% url 'postman:delete' %}'"><i class="fa fa-trash-o"></i></button>{% endblock %}
                            {% block pm_archive_button %}<button class="button_temp pull-right" type="submit" onclick="this.form.action='{% url 'postman:archive' %}'">{% trans "Archive" %}</button>{% endblock %}
                            {% block pm_undelete_button %}<button class="button_temp pull-right" type="submit" onclick="this.form.action='{% url 'postman:undelete' %}'">{% trans "Undelete" %}</button>{% endblock %}
                            {% block pm_read_button %}<button class="button_temp pull-right" type="submit" onclick="this.form.action='{% url 'postman:mark-read' %}'">{% trans "Mark as read" %}</button>{% endblock %}
                            {% block pm_unread_button %}<button class="button_temp pull-right" type="submit" onclick="this.form.action='{% url 'postman:mark-unread' %}'">{% trans "Mark as unread" %}</button>{% endblock %}
                            </span>{% endblock %}

                            <table id="pm_messages">
                            <thead>
                                <tr>
                                    <th id="th1" style="width: 20px">
                                        <!--{% trans "Action" %}-->
                                    </th>

                                    {% block pm_sender_header %}
                                    <th id="th2" style="width: 75px">
                                        <a href="{% postman_order_by sender %}">{% trans "Sender" %}</a>
                                        <div>&nbsp;</div>
                                    </th>{% endblock %}

                                    {% block pm_recipient_header %}
                                    <th id="th3" style="width: 75px">
                                        <a href="{% postman_order_by recipient %}">{% trans "Recipient" %}</a>
                                    </th>{% endblock %}

                                   <th id="th4" style="width: 250px">
                                       <a href="{% postman_order_by subject %}">{% trans "Subject" %}</a>
                                   </th>

                                   <th id="th5" style="width: 40px">
                                       <a href="{% postman_order_by date %}">{% block pm_date %}{% trans "Date" %}{% endblock %}</a>
                                   </th>
                                </tr>
                            </thead>
                            <tbody>{% for message in pm_messages %}
                                <tr>
                                    <td headers="th1">
                                        <input type="checkbox" {% if by_conversation and message.thread_id %}name="tpks" value="{{ message.thread_id }}"{% else %}name="pks" value="{{ message.pk }}"{% endif %} />
                                    </td>

                                    {% block pm_sender_cell %}
                                    <td headers="th2">
                                        {{ message.obfuscated_sender|or_me:user }}{% if message.count %} ({{ message.count }}){% endif %}
                                    </td>{% endblock %}

                                    {% block pm_recipient_cell %}
                                    <td headers="th3">
                                        {{ message.obfuscated_recipient|or_me:user }}{% if message.count %} ({{ message.count }}){% endif %}
                                    </td>{% endblock %}

                                    <td headers="th4">{% if message.is_new %}<strong>{% endif %}{% if message.is_replied %}<em>{% endif %}
                                        {% block pm_subject %}
                                        <a href="{% if by_conversation and message.thread_id %}{% url 'postman:view_conversation' message.thread_id %}{% else %}{% url 'postman:view' message.pk %}{% endif %}?next={{ current_url|urlencode }}">
                                            {% include "postman/inc_subject_ex.html" %}
                                        </a>
                                        {% endblock %}
                                        {% if message.is_replied %}</em>{% endif %}{% if message.is_new %}</strong>{% endif %}
                                    </td>

                                    <td headers="th5">
                                        {{ message.sent_at|compact_date:_("g:i A,M j,n/j/y") }}
                                    </td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </form>
                </div>
            </div>
            {% paginate %}
            {% else %}
            <p>{% trans "No messages." %}</p>
            {% endif %}
            {% endif %}
            {% block pm_footer_info %}{% endblock %}
            </div>
            {% endblock content %}
    <br>
    <br>
    <a class="button_temp" href="/messages/base" role="button" style="margin-left:375px">Back</a>

    {% endblock %}
    </body>
  
</html>

HealthNet/healthnet_BKZ/HealthNet/postman/templates/postman/sent.html
{% extends "postman/base_folder.html" %}
{% load staticfiles %}
{% load main_extras %}
<!DOCTYPE HTML>
<!--
	Minimaxing by HTML5 UP
	html5up.net | @ajlkn
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
<html>
	<head>
		<title>HealthNet - Profile</title>
		<link rel="shortcut icon" href="{% static 'main/images/bkz_io.png' %}"/>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<!--[if lte IE 8]><script src="assets/js/ie/html5shiv.js"></script><![endif]-->
		<!--[if lte IE 9]><link rel="stylesheet" href="assets/css/ie9.css" /><![endif]-->
		<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
		<link href="{% static 'css/bootstrap-theme.min.css' %}" rel="stylesheet">
		<script src="https://use.fontawesome.com/d4ff336425.js"></script>
		<link rel="stylesheet" href="{% static 'css/main.css' %}" >
		<link rel="stylesheet" href="{% static 'css/profile.css' %}" >
	</head>
    <body>

    <div>
        <div id="page-wrapper">
            <div id="header-wrapper">
                <div class="container_temp">
                    <div class="row_temp">
                        <div class="12u">
                            <header id="header">
                                <h1><a href="#" id="logo">HealthNet</a></h1>
                                <nav id="nav">
                                    <a href="{% url 'main:home' %}"><i class="fa fa-home"></i>       Home</a>
                                    {% if user|usercheck:"patient" %}
                                      <a href="/profile" class="current-page-item"><i class="fa fa-user"></i>   Profile</a>
                                    {% else %}
                                      <a href="/patients"><i class="fa fa-users"></i>   Patients</a>
                                    {% endif %}
                                    <a href="/calendar"><i class="fa fa-calendar"></i>    Calendar</a>
                                    <a href="/about"><i class="fa fa-info-circle"></i>   About</a>
                                    <a href="/messages/base"><i class="fa fa-envelope-o"></i>         Messages</a>
                                    <a href="/logout"><i class="fa fa-sign-out"></i>        &nbsp;Logout</div></a>
                             </header>
                        </div>
                    </div>
                </div>
            </div>
        </div>
{% load i18n %}
{% block pm_folder_title %}{% trans "Sent Messages" %}{% endblock %}
{% block pm_undelete_button %}{% endblock %}
{% block pm_read_button %}{% endblock %}
{% block pm_unread_button %}{% endblock %}
{% block pm_sender_header %}{% endblock %}
{% block pm_date %}{% trans "Sent" %}{% endblock %}
{% block pm_sender_cell %}{% endblock %}

    <br>
    <br>
    <a class="button_temp" href="/messages/base" role="button">Back</a>
    </body>
</html>

HealthNet/healthnet_BKZ/HealthNet/postman/templates/postman/trash.html
{% extends "postman/base_folder.html" %}
{% load staticfiles %}
{% load main_extras %}
<!DOCTYPE HTML>
<!--
	Minimaxing by HTML5 UP
	html5up.net | @ajlkn
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
<html>
	<head>
		<title>HealthNet - Profile</title>
		<link rel="shortcut icon" href="{% static 'main/images/bkz_io.png' %}"/>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<!--[if lte IE 8]><script src="assets/js/ie/html5shiv.js"></script><![endif]-->
		<!--[if lte IE 9]><link rel="stylesheet" href="assets/css/ie9.css" /><![endif]-->
		<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
		<link href="{% static 'css/bootstrap-theme.min.css' %}" rel="stylesheet">
		<script src="https://use.fontawesome.com/d4ff336425.js"></script>
		<link rel="stylesheet" href="{% static 'css/main.css' %}" >
		<link rel="stylesheet" href="{% static 'css/profile.css' %}" >
	</head>
    <body>

    <div>
        <div id="page-wrapper">
            <div id="header-wrapper">
                <div class="container_temp">
                    <div class="row_temp">
                        <div class="12u">
                            <header id="header">
                                <h1><a href="#" id="logo">HealthNet</a></h1>
                                <nav id="nav">
                                    <a href="{% url 'main:home' %}"><i class="fa fa-home"></i>       Home</a>
                                    {% if user|usercheck:"patient" %}
                                      <a href="/profile" ><i class="fa fa-user"></i>   Profile</a>
                                    {% else %}
                                      <a href="/patients"><i class="fa fa-users"></i>   Patients</a>
                                    {% endif %}
                                    <a href="/calendar"><i class="fa fa-calendar"></i>    Calendar</a>
                                    <a href="/about"><i class="fa fa-info-circle"></i>   About</a>
                                    <a href="/messages/base" class="current-page-item"><i class="fa fa-envelope-o"></i>         Messages</a>
                                    <a href="/logout"><i class="fa fa-sign-out"></i>        &nbsp;Logout</div></a>
                             </header>
                        </div>
                    </div>
                </div>
            </div>
        </div>
{% load i18n %}
{% block pm_folder_title %}{% trans "Deleted Messages" %}{% endblock %}
{% block pm_delete_button %}{% endblock %}
{% block pm_archive_button %}{% endblock %}
{% block pm_subject %}{# no link #}
     {% include "postman/inc_subject_ex.html" %}
{% endblock %}
{% block pm_footer_info %}
<p>{% trans "Messages in this folder can be removed from time to time. For long term storage, use instead the archive folder." %}</p>
{% endblock %}
    <br>
    <br>
    <a class="button_temp" href="/messages/base" role="button">Back</a>
    </body>
</html>

HealthNet/healthnet_BKZ/HealthNet/postman/templates/postman/view.html
{% extends 'main/base_nav.html' %}
{% load staticfiles %}
{% load main_extras %}
<!DOCTYPE HTML>
<!--
	Minimaxing by HTML5 UP
	html5up.net | @ajlkn
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
{% block page-title %} Messaging {% endblock %}
<html>
    <body>
    {% block main %}
    <div>
        <div id="page-wrapper">
            {% include 'main/navbar.html' %}
        </div>

        {% load i18n %}{% load postman_tags %}
        {% block content %}
        <div id="postman">
            <div class="container">
                <br>
                <div class="row">
                    <div class="well">
                        <h1>{% if pm_messages|length > 1 %}{% trans "Conversation" %}{% else %}{% trans "Message" %}{% endif %}</h1>
                        {% for message in pm_messages %}
                        <div class="pm_message">{% if message.is_pending %} pm_pending{% endif %}{% if message.is_rejected %} pm_rejected{% endif %}{% if message.sender == user and message.sender_archived or message.recipient == user and message.recipient_archived %} pm_archived{% endif %}{% if message.sender == user and message.sender_deleted_at or message.recipient == user and message.recipient_deleted_at %} pm_deleted{% endif %}{% if message.recipient == user and not message.read_at %} pm_unread{% endif %}
                            <div class="pm_header">
                                <span class="pm_sender">{{ message.obfuscated_sender|or_me:user }}</span> &raquo;
                                <span class="pm_recipient">{{ message.obfuscated_recipient|or_me:user }}</span> |
                                <span class="pm_date">{{ message.sent_at|date:"DATETIME_FORMAT"}}</span> |
                                <span class="pm_subject">{{ message.subject }}</span>
                                {% if message.is_rejected %}
                                <div class="pm_status">
                                    {% trans "Rejected" %}{% if message.moderation_reason %}{% trans ":" %} {{ message.moderation_reason }}{% endif %}
                                </div>{% endif %}
                            </div>
                            <div class="pm_body">{{ message.body|linebreaksbr }}</div>
                        </div>
                        {% if forloop.last %}
                        <form action="" method="post">{% csrf_token %}
                            <input type="hidden" {% if pm_messages|length > 1 and message.thread_id %}name="tpks" value="{{ message.thread_id }}"{% else %}name="pks" value="{{ message.pk }}"{% endif %} />
                            <br>
                            <span id="pm_buttons">
                                <button class="button_temp" type="submit" onclick="this.form.action='{% url 'postman:delete' %}?next={{ next_url|urlencode }}'">{% trans "Delete" %}</button>
                                {% if not archived %}<button class="button_temp" type="submit" onclick="this.form.action='{% url 'postman:archive' %}?next={{ next_url|urlencode }}'">{% trans "Archive" %}</button>{% endif %}
                            </span>
                        </form>
                        {% if reply_to_pk %}<hr />
                        <h2>{% trans 'Reply' %}</h2>
                        <form action="{% url 'postman:reply' reply_to_pk %}?next={{ next_url|urlencode }}" method="post">{% csrf_token %}
                            <div id="pm_reply">{{ form.body }}</div>
                            <a class="button_temp" href="{{ next_url }}">{% trans "Back" %}</a>
                            <button class="button_temp" type="submit">{% trans 'Reply' %}</button>
                        </form>{% endif %}
                        {% endif %}
                        {% endfor %}
                    </div>
                    {% endblock %}
                </div>
            </div>
        </div>
    {% endblock %}
    </body>
</html>