HealthNet/healthnet_BKZ/HealthNet/HealthNet/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    # URL for Djangos login solution, also currently the splash page
    url(r'^login', 'django.contrib.auth.views.login', name='login'),
    url(r'^admin/', admin.site.urls),
    url(r'^', include('main.urls')),
    url(r'^', include('fullcalendar.urls', namespace="fullcalendar")),
    url(r'^messages/', include('postman.urls', namespace="postman", app_name='postman'))

]

HealthNet/healthnet_BKZ/HealthNet/fullcalendar/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.auth.decorators import login_required
from django.contrib import admin
from . import views
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^calendar/filtered_events', 'fullcalendar.views.filtered_events', name='filtered_events'),
    url(r'^calendar/', 'fullcalendar.views.index', name='index'),
    url(r'^all_events/', 'fullcalendar.views.all_events', name='all_events'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^appointment/(?P<pk>[0-9]+)', login_required(views.AppointmentView.as_view()), name='detail'),
    url(r'^editAppointment/(?P<pk>[0-9]+)', login_required(views.AppointmentEdit.as_view()), name='editAppointment'),
    url(r'^verifyAppointment/(?P<pk>[0-9]+)', login_required(views.AppointmentVerify.as_view()),
        name='verifyAppointment'),
    url(r'^makeAppointment/$', views.CreateAppointmentView.as_view(), name='makeAppointment'),
    url(r'^deleteAppointment/(?P<pk>[0-9]+)$', login_required(views.DeleteAppointment.as_view()),
        name='deleteAppointment')
)

HealthNet/healthnet_BKZ/HealthNet/main/urls.py
from django.conf.urls import url
from django.conf import settings
from . import views
from log.views import *
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.auth.decorators import login_required


app_name = 'main'

# url's for main application
urlpatterns = [
    # URL for Djangos logout solution, redirects to our own success page after logging them out
    url(r'^logout/$', 'django.contrib.auth.views.logout', {'next_page': '/logout_success/'}),
    # Landing page for logging out users
    url(r'^logout_success/$', views.LogoutSuccess.as_view(), name='logout_success'),
    # URL for the profile page
    url(r'^profile/$', views.profileView, name='profile'),
    # URL for the about page
    url(r'^about/$', login_required(views.AboutView), name='about'),
    # URL for new Home Page
    url(r'^$', views.HomeView.as_view(), name='home'),
    # URL for the contact page
    url(r'^contact/$', login_required(views.ContactView.as_view()), name='contact'),
    # URL for the edit profile page
    url(r'^edit_profile/$', login_required(views.ProfileUpdateView.as_view()), name='edit_profile'),
    # URL for the regrestration page
    url(r'^register/$', views.RegisterView.as_view(), name='register1'),
    # URL for the message doctor page
    url(r'^message/$', login_required(views.MessageView.as_view()), name='message'),
    # URL for the prescriptions page
    url(r'^prescription/(?P<pk>[0-9]+)$', login_required(views.WritePrescriptionView.as_view()), name='prescribe'),
    # URL to access the admin page
    url(r'^adminc/$', AdminView, name='adminc'),
    url(r'^staffregist/$', login_required(StaffRegisterView.as_view()), name='staffregist'),
    url(r'^hospital/(?P<pk>[0-9]+)$', login_required(HospitalStatView.as_view()), name='hospital'),
    # URL for the Test page
    url(r'^test/(?P<pk>[0-9]+)$', login_required(views.TestCreateView.as_view()), name='test'),
    url(r'^editTest/(?P<pk>[0-9]+)$', login_required(views.TestEditView.as_view()), name='editTest'),
    url(r'^deleteTest/(?P<pk>[0-9]+)$', login_required(views.DeleteTest.as_view()),
        name='deleteTest'),
    url(r'^releaseTest/(?P<pk>[0-9]+)$', login_required(views.TestReleaseView.as_view()),
        name='releaseTest'),
    url(r'^deletePrescription/(?P<pk>[0-9]+)$', login_required(views.DeletePrescription.as_view()),
        name='deletePrescription'),
    # URL for the view_patient page
    url(r'^view_patient/(?P<pk>[0-9]+)$', login_required(views.PatientView.as_view()), name='viewPatient'),
    url(r'^discharge_patient/(?P<pk>[0-9]+)$', login_required(views.DischargePatientView.as_view()), name='discharge'),
    url(r'^transfer_patient/(?P<pk>[0-9]+)$', login_required(views.TransferPatientView.as_view()), name='transfer'),
    url(r'^admit_patient/(?P<pk>[0-9]+)$', login_required(views.AdmitPatientView.as_view()), name='admit'),
    #URL for the page the patient list page
    url(r'^patients/$', login_required(views.PatientListView.as_view()), name='patients'),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT,}),
    url(r'confirm_download/$', login_required(views.ConfirmDownloadView.as_view()), name='confirm_download'),
    url(r'confirm_test_download/$', login_required(views.ConfirmTestDownloadView.as_view()), name='confirm_test_download'),
    url(r'download_info/$', login_required(views.DownloadProfileView), name='download'),
    url(r'download_test_info/$', login_required(views.DownloadTestView), name='download_test_info')
]

urlpatterns += staticfiles_urlpatterns()
#urlpatterns += static(settings.MEDIA_URL, document_root=MEDIA_ROOT)

HealthNet/healthnet_BKZ/HealthNet/main/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.views import generic
from HealthNet import customLog
from django.contrib.auth import authenticate, login
from django.core.urlresolvers import reverse_lazy, reverse
from django.contrib.auth.decorators import login_required
from django.views.generic.base import ContextMixin
from django.core.exceptions import PermissionDenied
from django.core.mail import send_mail
from HealthNet.settings import BASE_DIR

import logging
import random
import csv
import zipfile
import io

from .models import *
from .forms import *


logger = logging.getLogger(__name__)


# Forbids access if user is not a doctor, admin, or nurse.
class StaffOnlyMixin(ContextMixin):
    def dispatch(self, request, *args, **kwargs):
        user = request.user
        if hasattr(user, 'doctor') or hasattr(user, 'nurse') or user.is_superuser:
            return super(generic.ListView, self).dispatch(request, *args, **kwargs)
        else:
           raise PermissionDenied


class FormMixin(ContextMixin):
    def form_invalid(self, form):
        logger.error('Something went wrong!')
        return self.render_to_response(self.get_context_data(form=form))


class LogoutSuccess(generic.TemplateView):
    template_name = 'main/logout.html'  


@login_required
def profileView(request):
    if hasattr(request.user, 'doctor') or hasattr(request.user, 'nurse'):
        return redirect('/patients/')
    if request.user.is_superuser:
        return redirect('/admin/')
    template = loader.get_template('main/profile.html')

    # Sets the object the page is displaying to the current user.
    u = request.user
    # Gets the context list for use in the HTML template
    context = {
        'username': u.username,
        'email': u.email,
        'first_name': u.first_name,
        'last_name': u.last_name,
        'address_line1': u.patient.address_line1,
        'address_line2': u.patient.address_line2,
        'address_city': u.patient.address_city,
        'address_region': u.patient.address_region,
        'address_zip': u.patient.address_zip,
        'address_country': u.patient.address_country,
        'insurance_company': u.patient.insurance_company,
        'insurance_number': u.patient.insurance_number,
        'ID': u.patient.ID,
        'medical_conditions': u.patient.medical_conditions,
        'preferred_hospital': u.patient.preferred_hospital,
        'emergency_contact': u.patient.emergency_contact,
        'emergency_contact_number': u.patient.emergency_contact_number,
        'admitted_hospital': u.patient.admitted_hospital,
        'prescriptions': Prescription.objects.filter(patient=u.patient),
        'tests': Test.objects.filter(testPatient=u.patient),
        }
    return HttpResponse(template.render(context, request))


class TestCreateView(generic.FormView):
    template_name = 'main/createtest.html'
    form_class = TestForm

    def get_success_url(self):
        return reverse('main:viewPatient', kwargs={'pk': self.patient.ID})

    def dispatch(self, request, *args, **kwargs):
        self.patient = self.get_patient()
        return super(TestCreateView, self).dispatch(request, *args, **kwargs)

    def get_patient(self):
        return Patient.objects.get(pk=self.kwargs['pk'])

    def get_initial(self):
        initial = {'test_doctor': self.request.user.doctor.get_name(), }
        return initial

    def form_valid(self, form):
        test_name = form.cleaned_data['test_name']
        test_comment = form.cleaned_data['test_comment']
        test_image = form.cleaned_data['test_image']
        test_doctor = form.cleaned_data['test_doctor']
        test = Test.objects.create(testName=test_name,
                                   testPatient=self.patient,
                                   testComment=test_comment,
                                   testImage=test_image,
                                   testDoctor=test_doctor,
                                   )
        test.save()
        customLog.add_log("User %s test added" % (test.testPatient.user.username), 'TESTCR')
        return super(TestCreateView, self).form_valid(form)


class TestReleaseView(generic.FormView):
    template_name = 'main/viewtest.html'
    form_class = BooleanForm

    def dispatch(self, request, *args, **kwargs):
        self.kwargs['patient'] = Patient.objects.get(test__pk=self.kwargs['pk']).ID
        self.test = self.get_test()
        return super(TestReleaseView, self).dispatch(request, *args, **kwargs)

    def get_success_url(self):
        return '/view_patient/'+str(Patient.objects.get(test__pk=self.kwargs['pk']).ID)

    def get_test(self):
        return Test.objects.get(pk=self.kwargs['pk'])

    def form_valid(self, form):
        self.test.testReleased = form.cleaned_data['confirm']
        self.test.save()
        return super(TestReleaseView, self).form_valid(form)

class TestEditView(generic.FormView):
    template_name = 'main/edittest.html'
    form_class = TestForm

    def get_form(self, form_class=None):
        form = super(TestEditView, self).get_form(form_class)
        form.fields.pop('test_name')
        return form

    def dispatch(self, request, *args, **kwargs):
        self.kwargs['patient'] = Patient.objects.get(test__pk=self.kwargs['pk']).ID
        self.test = self.get_test()
        return super(TestEditView, self).dispatch(request, *args, **kwargs)

    def get_success_url(self):
        return '/view_patient/'+str(Patient.objects.get(test__pk=self.kwargs['pk']).ID)

    def get_test(self):
        return Test.objects.get(pk=self.kwargs['pk'])

    def get_initial(self):
        initial = {'test_doctor': self.test.testDoctor,
                   'test_name': self.test.testName,
                   'test_comment': self.test.testComment,
                   'test_image': self.test.testImage,
                   }
        return initial

    def form_valid(self, form):
        self.test.testComment = form.cleaned_data['test_comment']
        self.test.testImage = form.cleaned_data['test_image']
        self.test.save()
        customLog.add_log("User %s test edited" % (self.test.testPatient.user.username), 'TESTED')
        return super(TestEditView, self).form_valid(form)



class DeleteTest(generic.DeleteView):
    model = Test
    template_name = 'main/test_confirm_delete.html'

    def dispatch(self, request, *args, **kwargs):
        self.kwargs['patient'] = Patient.objects.get(test__pk=self.kwargs['pk']).ID
        return super(DeleteTest, self).dispatch(request, *args, **kwargs)

    def get_success_url(self):
        return '/view_patient/'+str(Patient.objects.get(test__pk=self.kwargs['pk']).ID)

    def delete(self, request, *args, **kwargs):
        if hasattr(self.request.user, 'nurse') or hasattr(self.request.user, 'patient'):
            raise PermissionDenied
        else:
            customLog.add_log("%s deleted Test with ID %s" % (self.request.user.username, self.kwargs['pk']),
                              'TESTDL')
            return super(DeleteTest, self).delete(request, *args, **kwargs)


class WritePrescriptionView (generic.FormView):
    template_name = 'main/prescription.html'
    form_class = PrescriptionForm

    def get_success_url(self):
        return reverse('main:viewPatient', kwargs={'pk': self.patient.ID})

    def dispatch(self, request, *args, **kwargs):
        self.patient = self.get_patient()
        return super(WritePrescriptionView, self).dispatch(request, *args, **kwargs)

    def get_patient(self):
        return Patient.objects.get(pk=self.kwargs['pk'])


    def get_initial(self):
        initial = {'prescribing_doctor': self.request.user.doctor.get_name(),
                   'patient': Patient.objects.get(pk=self.kwargs['pk']),}
        return initial

    def form_valid(self, form):
        #patient = form.cleaned_data['patient']
        medication_name = form.cleaned_data['medication_name']
        medication_directions = form.cleaned_data['medication_directions']
        medication_amount = form.cleaned_data['medication_amount']
        medication_type = form.cleaned_data['medication_type']
        medication_refills = form.cleaned_data['medication_refills']
        prescribing_doctor = form.cleaned_data['prescribing_doctor']

        prescription = Prescription.objects.create(patient=self.patient,
                                                   medicationName=medication_name,
                                                   medicationDirections=medication_directions,
                                                   medicationAmount=medication_amount,
                                                   medicationType=medication_type,
                                                   medicationRefills=medication_refills,
                                                   prescribingDoctor=prescribing_doctor)
        prescription.save()
        customLog.add_log("User %s prescription added" % (prescription.patient.user.username), 'PRESCRB')
        return super(WritePrescriptionView, self).form_valid(form)


class DeletePrescription(generic.DeleteView):
    model = Prescription
    template_name = 'main/prescription_confirm_delete.html'

    def dispatch(self, request, *args, **kwargs):
        self.kwargs['patient'] = Patient.objects.get(prescription__ID=self.kwargs['pk']).ID
        return super(DeletePrescription, self).dispatch(request, *args, **kwargs)

    def get_success_url(self):
        return '/view_patient/'+str(Patient.objects.get(prescription__ID=self.kwargs['pk']).ID)

    def delete(self, request, *args, **kwargs):
        if hasattr(self.request.user, 'nurse') or hasattr(self.request.user, 'patient'):
            raise PermissionDenied
        else:
            customLog.add_log("%s deleted prescription with ID %s" % (self.request.user.username, self.kwargs['pk']),
                              'PRESCRP')

HealthNet/healthnet_BKZ/HealthNet/main/templates/main/about3.html
{% load staticfiles %}
{% load main_extras %}
<!DOCTYPE HTML>
<!--
	Minimaxing by HTML5 UP
	html5up.net | @ajlkn
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
<html>
	<head>
		<title>HealthNet - About</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<!--[if lte IE 8]><script src="assets/js/ie/html5shiv.js"></script><![endif]-->
		<!--[if lte IE 9]><link rel="stylesheet" href="assets/css/ie9.css" /><![endif]-->
		<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
		<link href="{% static 'css/bootstrap-theme.min.css' %}" rel="stylesheet">
		<script src="https://use.fontawesome.com/d4ff336425.js"></script>
		<link rel="stylesheet" href="{% static 'css/main.css' %}" >
		<link rel="stylesheet" href="{% static 'css/about.css' %}" >
	</head>
	<body>
		<div id="page-wrapper">
			<div id="header-wrapper">
				<div class="container_temp">
					<div class="row_temp">
						<div class="12u">
							<header id="header">
								<h1><a href="#" id="logo">HealthNet</a></h1>
								<nav id="nav">
									<a href="{% url 'main:home' %}"><i class="fa fa-home"></i>&nbsp;&nbsp;&nbsp;&nbsp;Home</a>
                                    {% if user|usercheck:"patient" %}
                                        <a href="/profile"><i class="fa fa-user"></i>&nbsp;&nbsp;&nbsp;&nbsp;Profile</a>
                                    {% else %}
                                        <a href="/patients"><i class="fa fa-users"></i>&nbsp;&nbsp;&nbsp;&nbsp;Patients</a>
                                    {% endif %}
									<a href="/calendar"><i class="fa fa-calendar"></i>&nbsp;&nbsp;&nbsp;&nbsp;Calendar</a>
									<a href="/about"  class="current-page-item"><i class="fa fa-info-circle"></i>   About</a>
									<a href="/messages/base"><i class="fa fa-envelope-o"></i>&nbsp;&nbsp;&nbsp;&nbsp;Messages</a>
									<a href="/logout"><i class="fa fa-sign-out"></i>&nbsp;&nbsp;&nbsp;&nbsp;Logout</div></a>
								</nav>
							</header>

						</div>
					</div>
				</div>
			</div>
			<div class="main">
				<div class="row" style="margin:20px;"></div>
				    <p class="well" style="width:150px">Site made by:</p>

    				<img src="{% static 'main/images/BKZ.png' %}">
			</div>
			<div class="row">
				<div class="12u">
					<div id="copyright">
						&copy; Untitled. All rights reserved. | Design: <a href="http://html5up.net">HTML5 UP</a>
					</div>
				</div>
			</div>


			<!-- Scripts -->
			<script src="assets/js/jquery.min.js"></script>
			<script src="assets/js/skel.min.js"></script>
			<script src="assets/js/skel-viewport.min.js"></script>
			<script src="assets/js/util.js"></script>
			<!--[if lte IE 8]><script src="assets/js/ie/respond.min.js"></script><![endif]-->
			<script src="assets/js/main.js"></script>

	</body>
</html>

HealthNet/healthnet_BKZ/HealthNet/main/templates/main/edit_profile.html
{% extends 'main/base_nav.html' %}
{% load staticfiles %}
{% load main_extras %}
<!--
	Minimaxing by HTML5 UP
	html5up.net | @ajlkn
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
	{% block page-title %} Edit Profile {% endblock %}
		{% block head %}
			<link rel="stylesheet" href="{% static 'css/edit_profile.css' %}" >
		{% endblock %}

	<body>
		<div id="page-wrapper">
			{% block main %}
			{% include 'main/navbar.html' %}
			<div class="main">
				<div class="row" style="margin: 20px;"></div>
				<div class="container">
					<div class="row">
						<div class="col-sm-2">
					    	<img class="img_prof" src="{{ MEDIA_URL }}{{ request.user.patient.avatar.url }}" alt="generic"  style="margin-bottom:10px;border: solid #000 3px; border-radius: 5px; width: 100%; margin-top: auto"/>
						</div>
						<div class="col-sm-10">
							<h3>
								{{request.user.first_name}} {{request.user.last_name}}
							</h3>
						</div>
					</div>
			    </div>
			    {% if form.errors %}
			        <!-- Error messaging -->
			            <div id="errors">
			                <div class="inner" >
			                    <p>There were some errors in the information you entered. Please correct the following:</p>
			                    {{ form.non_field_errors }}
			                    <ul>
			                        {% for field in form %}
			                            {% if field.errors %}<li>{{ field.label }}: {{ field.errors|striptags }}</li>{% endif %}
			                        {% endfor %}
			                    </ul>
			                </div>
			            </div>
				<!-- /Error messaging -->
			    {% endif %}

			    <form enctype="multipart/form-data" action="{% url 'main:edit_profile'%}" method="post"> <!-- start form -->
			        {% csrf_token %}
			        <div class="row">
			            <div class="col-sm-1"></div>
			            <div class="col-sm-4">
                            {{ form.avatar }}
			            </div>
			            <div class="col-sm-1"></div>
			            <div class="col-sm-4">
			                Password:<br>
			                {{ form.password }}
                            {{ form.password_confirm }}
			            </div>
			        </div>
			        <div class="row">
			            <div class="col-sm-1"></div>
			            <div class="col-sm-4">
			                First Name:<br>
			                {{ form.first_name }}
			            </div>
			            <div class="col-sm-1"></div>
			            <div class="col-sm-4">
			                Last Name:<br>
			                {{ form.last_name }}
			            </div>
			        </div>
			        <div class="row">
			            <div class="col-sm-1"></div>
			            <div class="col-sm-4">
			                Email:<br>
			                {{ form.email }}
			            </div>
			            <div class="col-sm-1"></div>
			            <div class="col-sm-4">
			                Preferred Hospital:<br>
			                {{ form.preferred_hospital }}
			            </div>
			        </div>
			        <div class="row">
			            <div class="col-sm-1"></div>
			            <div class="col-sm-4">
			                Date of Birth:<br>
			                {{ form.date_of_birth }}

			            </div>
			            <div class="col-sm-1"></div>
			            <div class="col-sm-4">
			                Address:<br>
			                {{ form.address1 }}
							{{ form.address2 }}
							{{ form.city }}
							{{ form.region }}
							{{ form.zip }}
							{{ form.country }}
						</div>
			            </div>
			        </div>
			        <div class="row">
			            <div class="col-sm-1"></div>
			            <div class="col-sm-4">
			                Insurance:<br>
			                {{ form.insurance_company }}
			                {{ form.insurance_number }}
			            </div>
			            <div class="col-sm-1"></div>
			            <div class="col-sm-4">
			                Emergency Contact:<br>
			                {{ form.emergency_contact_name }}
			                {{ form.emergency_phone_number }}
			            </div>
			        </div>
			        <div class="row">
			            <div class="col-sm-1"></div>
			            <div class="col-sm-4">
			                Medical Conditions:<br>
			                {{ form.medical_conditions }}
			            </div>
			        </div>
			        <input class="button_temp pull-right" type="submit" name="edit" value="Submit" style="margin-right: 10px;"/>
			        <a class="button_temp pull-left" href="{% url 'main:profile' %}" role="button" style="margin-left: 10px;">Back</a>

			    </form><!-- end form -->
			    <div class="row" style="margin: 20px;"></div>
			</div>
			<div class="row">
				<div class="12u">
					<div id="copyright">
						&copy; Untitled. All rights reserved. | Design: <a href="http://html5up.net">HTML5 UP</a>
					</div>
				</div>
			{% endblock %}
			</div>


			<!-- Scripts -->
			<script src="assets/js/jquery.min.js"></script>
			<script src="assets/js/skel.min.js"></script>
			<script src="assets/js/skel-viewport.min.js"></script>
			<script src="assets/js/util.js"></script>
			<!--[if lte IE 8]><script src="assets/js/ie/respond.min.js"></script><![endif]-->
			<script src="assets/js/main.js"></script>

	</body>

HealthNet/healthnet_BKZ/HealthNet/main/templates/main/logout.html
{% extends 'main/base_nav.html' %}
{% load staticfiles %}
{% load main_extras %}

{% block page-title %} Logout {% endblock page-title %}

{% block head %}
	<link rel="stylesheet" href="{% static 'css/profile.css' %}" >
{% endblock head %}

{% block main %}
		<div id="page-wrapper">
			<div id="header-wrapper">
				<div class="row" style="margin:20px;"></div>
			</div>
			<div class="main">
				<div class="container">
				    <div class="row">
						<div class="col-sm-12 well">
							<p>
								Logout Successful!
							</p>
						<a href="/"><div class="btn btn-default pull-right" role="button">Home</div></a>
						</div>
					</div>
					</div>
							</div>
							<div class="row">
								<div class="12u">
									<div id="copyright">
										&copy; Untitled. All rights reserved. | Design: <a href="http://html5up.net">HTML5 UP</a>
									</div>
								</div>
			</div>

{% endblock main %}

HealthNet/healthnet_BKZ/HealthNet/main/templates/main/makeAppointment.html
{% extends 'main/base_nav.html' %}
{% load staticfiles %}
{% load main_extras %}

{% block page-title %} Make Appointment {% endblock page-title %}
		
{% block main %}
		<div id="page-wrapper">
			{% include 'main/navbar.html' %}
			<div class="main">
				<form method = 'post'>
					{% csrf_token %}
					<div class="well">
						<h2>Make an Appointment</h2>
					</div>

					<div class="container">
						<div class="row">
							<div>
								{{ form.hospital }}
							</div>
						</div>
						<div class="row">
							<div>
								{{ form.doctor }}
							</div>
						</div>
						<div class="row">
							<div>
								{{ form.start_date }}
							</div>
						</div>

						<div class="row">
							<div>
								{{ form.start_time }}
							</div>
						</div>

						<div class="row">
							<div>
								{{ form.description }}
							</div>
						</div>

						<div class="row">
							<div>
								{{ form.patient }}
							</div>
						</div>


						<div class="row">
							<div>
								{{form.verified.label_tag}}
								{{ form.verified }}

							</div>
						</div>
					</div>
					<div class="row" style="margin-top: 20px"></div>

					<input class="button_temp pull-right" role="button" type="submit" value="Submit" style="margin-right: 375px"/>
					<a class="button_temp pull-left" href="{% url 'fullcalendar:index' %}" role= "button" style="margin-left: 375px">Back</a>
					<div class="row" style="margin:5px;"></div>


					<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
					<!-- Include all compiled plugins (below), or include individual files as needed -->
					<script src="js/bootstrap.min.js"></script>
					</form>
			</div>
			<div class="row">
				<div class="12u">
					<div id="copyright">
						&copy; Untitled. All rights reserved. | Design: <a href="http://html5up.net">HTML5 UP</a>
					</div>
				</div>
			</div>
{% endblock main %}

HealthNet/healthnet_BKZ/HealthNet/main/templates/main/navbar.html
{% load staticfiles %}
{% load main_extras %}
<div id="header-wrapper">
	<div class="container_temp">
		<div class="row_temp">
			<div class="12u">
				<header id="header">
					<h1><a href="#" id="logo">HealthNet</a></h1>
					<nav id="nav">
                        {% if user.is_authenticated %}
                            <a href="{% url 'main:home' %}"  class="{if view.__class__.__name__ == HomeView}"><i class="fa fa-home"></i>&nbsp;&nbsp;Home</a>
                            {% if request.user.is_superuser %}
                                 <a href="/adminc" class="{% block admin-active %}{% endblock %}"><i class="fa fa-cogs"></i>&nbsp;&nbsp;Admin</a>
                                {% endif %}
                            {% if user|usercheck:"patient" %}
                                <a href="/profile" class="{% block profile-active %}{% endblock %}"><i class="fa fa-user"></i>&nbsp;&nbsp;Profile</a>
                            {% else %}
                             <a href="/patients" class="{% block patients-active %}{% endblock %}"><i class="fa fa-users"></i>&nbsp;&nbsp;Patients</a>
                            {% endif %}
						    <a href="/calendar" class="{% block cal-active %}{% endblock %}"><i class="fa fa-calendar"></i>&nbsp;&nbsp;Calendar</a>
						    <a href="/messages/base" class="{% block mess-active %}{% endblock %}"><i class="fa fa-envelope-o"></i>&nbsp;&nbsp;Messages</a>
                            <a href="/logout"><i class="fa fa-sign-out"></i>&nbsp;&nbsp;Logout</a>
                        {% else %}
                            <a href="{% url 'login' %}"><i class="fa fa-sign-in"></i>&nbsp;&nbsp;Login/Register</a>
                        {% endif %}
					</nav>
				</header>
			</div>
		</div>
	</div>
</div>
