HealthNet/healthnet_BKZ/HealthNet/HealthNet/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    # URL for Djangos login solution, also currently the splash page
    url(r'^login', 'django.contrib.auth.views.login', name='login'),
    url(r'^admin/', admin.site.urls),
    url(r'^', include('main.urls')),
    url(r'^', include('fullcalendar.urls', namespace="fullcalendar")),
    url(r'^messages/', include('postman.urls', namespace="postman", app_name='postman'))

]

HealthNet/healthnet_BKZ/HealthNet/fullcalendar/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.auth.decorators import login_required
from django.contrib import admin
from . import views
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^calendar/filtered_events', 'fullcalendar.views.filtered_events', name='filtered_events'),
    url(r'^calendar/', 'fullcalendar.views.index', name='index'),
    url(r'^all_events/', 'fullcalendar.views.all_events', name='all_events'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^appointment/(?P<pk>[0-9]+)', login_required(views.AppointmentView.as_view()), name='detail'),
    url(r'^editAppointment/(?P<pk>[0-9]+)', login_required(views.AppointmentEdit.as_view()), name='editAppointment'),
    url(r'^verifyAppointment/(?P<pk>[0-9]+)', login_required(views.AppointmentVerify.as_view()),
        name='verifyAppointment'),
    url(r'^makeAppointment/$', views.CreateAppointmentView.as_view(), name='makeAppointment'),
    url(r'^deleteAppointment/(?P<pk>[0-9]+)$', login_required(views.DeleteAppointment.as_view()),
        name='deleteAppointment')
)

HealthNet/healthnet_BKZ/HealthNet/main/urls.py
from django.conf.urls import url
from django.conf import settings
from . import views
from log.views import *
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.auth.decorators import login_required


app_name = 'main'

# url's for main application
urlpatterns = [
    # URL for Djangos logout solution, redirects to our own success page after logging them out
    url(r'^logout/$', 'django.contrib.auth.views.logout', {'next_page': '/logout_success/'}),
    # Landing page for logging out users
    url(r'^logout_success/$', views.LogoutSuccess.as_view(), name='logout_success'),
    # URL for the profile page
    url(r'^profile/$', views.profileView, name='profile'),
    # URL for the about page
    url(r'^about/$', login_required(views.AboutView), name='about'),
    # URL for new Home Page
    url(r'^$', views.HomeView.as_view(), name='home'),
    # URL for the contact page
    url(r'^contact/$', login_required(views.ContactView.as_view()), name='contact'),
    # URL for the edit profile page
    url(r'^edit_profile/$', login_required(views.ProfileUpdateView.as_view()), name='edit_profile'),
    # URL for the regrestration page
    url(r'^register/$', views.RegisterView.as_view(), name='register1'),
    # URL for the message doctor page
    url(r'^message/$', login_required(views.MessageView.as_view()), name='message'),
    # URL for the prescriptions page
    url(r'^prescription/(?P<pk>[0-9]+)$', login_required(views.WritePrescriptionView.as_view()), name='prescribe'),
    # URL to access the admin page
    url(r'^adminc/$', AdminView, name='adminc'),
    url(r'^staffregist/$', login_required(StaffRegisterView.as_view()), name='staffregist'),
    url(r'^hospital/(?P<pk>[0-9]+)$', login_required(HospitalStatView.as_view()), name='hospital'),
    # URL for the Test page
    url(r'^test/(?P<pk>[0-9]+)$', login_required(views.TestCreateView.as_view()), name='test'),
    url(r'^editTest/(?P<pk>[0-9]+)$', login_required(views.TestEditView.as_view()), name='editTest'),
    url(r'^deleteTest/(?P<pk>[0-9]+)$', login_required(views.DeleteTest.as_view()),
        name='deleteTest'),
    url(r'^releaseTest/(?P<pk>[0-9]+)$', login_required(views.TestReleaseView.as_view()),
        name='releaseTest'),
    url(r'^deletePrescription/(?P<pk>[0-9]+)$', login_required(views.DeletePrescription.as_view()),
        name='deletePrescription'),
    # URL for the view_patient page
    url(r'^view_patient/(?P<pk>[0-9]+)$', login_required(views.PatientView.as_view()), name='viewPatient'),
    url(r'^discharge_patient/(?P<pk>[0-9]+)$', login_required(views.DischargePatientView.as_view()), name='discharge'),
    url(r'^transfer_patient/(?P<pk>[0-9]+)$', login_required(views.TransferPatientView.as_view()), name='transfer'),
    url(r'^admit_patient/(?P<pk>[0-9]+)$', login_required(views.AdmitPatientView.as_view()), name='admit'),
    #URL for the page the patient list page
    url(r'^patients/$', login_required(views.PatientListView.as_view()), name='patients'),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT,}),
    url(r'confirm_download/$', login_required(views.ConfirmDownloadView.as_view()), name='confirm_download'),
    url(r'confirm_test_download/$', login_required(views.ConfirmTestDownloadView.as_view()), name='confirm_test_download'),
    url(r'download_info/$', login_required(views.DownloadProfileView), name='download'),
    url(r'download_test_info/$', login_required(views.DownloadTestView), name='download_test_info')
]

urlpatterns += staticfiles_urlpatterns()
#urlpatterns += static(settings.MEDIA_URL, document_root=MEDIA_ROOT)

HealthNet/healthnet_BKZ/HealthNet/fullcalendar/forms.py
from django.forms import Form
from django import forms
from .models import *


class AppointmentForm(Form):
    hospital = forms.ModelChoiceField(widget=forms.Select(attrs={'class':'form-control'}),queryset=Hospital.objects.all())
    description = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Description','class':'form-control'}))
    start_date = forms.DateField(required=True,
                                 widget=forms.SelectDateWidget(attrs={'class':'form-control'},years=range(timezone.now().year,
                                                                           timezone.now().year + 10)))
    start_time = forms.TimeField(required=True,
                                 widget=forms.TimeInput(attrs={'placeholder': 'Time: HH:MM', 'class':'form-control'},
                                                        format='%H:%M'))
    # end_date = forms.DateField(required=True,
    #                            widget=forms.SelectDateWidget(years=range(1818, timezone.now().year+1)))
    # end_time = forms.TimeField(required=True,
    #                            widget=forms.TimeInput(format='%H:%M'))


class PatientAppointment(AppointmentForm):
    doctor = forms.ModelChoiceField(widget=forms.Select(attrs={'class':'form-control'}),queryset=Doctor.objects.all())


class DoctorAppointment(AppointmentForm):
    patient = forms.ModelChoiceField(queryset=Patient.objects.all())


class NurseAppointment(AppointmentForm):
    patient = forms.ModelChoiceField(queryset=Patient.objects.all())
    doctor = forms.ModelChoiceField(queryset=Doctor.objects.all())


HealthNet/healthnet_BKZ/HealthNet/fullcalendar/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import CalendarEvent
from .util import events_to_json, calendar_options
from main.views import FormMixin
from main.forms import BooleanForm
from django.views import generic
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from .forms import *
from django.core.exceptions import PermissionDenied
from datetime import datetime
from django.core.urlresolvers import reverse_lazy, reverse
from HealthNet import customLog
from postman.models import *

OPTIONS = """{  timeFormat: "H:mm",
                header: {
                    left: 'prev,next today',
                    center: 'title',
                    right: 'month,agendaWeek,agendaDay',
                },
                allDaySlot: false,
                firstDay: 1,
                weekMode: 'liquid',
                slotMinutes: 15,
                defaultEventMinutes: 30,
                minTime: 0,
                maxTime: 24,
                editable: false,
                dayClick: function(date, allDay, jsEvent, view) {
                    if (allDay) {
                        $('#calendar').fullCalendar('gotoDate', date)
                        $('#calendar').fullCalendar('changeView', 'agendaDay')
                    }
                },
                eventClick: function(event, jsEvent, view) {
                    window.location.href = '/appointment/'+event.id;
                },
            }"""


def index(request):
    event_url = 'filtered_events'
    return render(request, 'FullCalendar/index.html', {'calendar_config_options': calendar_options(event_url, OPTIONS)})

def all_events(request):
    # Use some decorator so only admins can access this URL?

    events = CalendarEvent.objects.all()
    return HttpResponse(events_to_json(events), content_type='application/json')

@login_required
def filtered_events(request):
    user = request.user
    events = CalendarEvent.objects.all()

    if hasattr(user, 'patient'):
        events = CalendarEvent.objects.all().filter(patient=user.patient)
    elif hasattr(user, 'doctor'):
        events = CalendarEvent.objects.all().filter(doctor=user.doctor)
    elif hasattr(user, 'nurse'):
        events = CalendarEvent.objects.all().filter(hospital=user.nurse.hospital)

    return HttpResponse(events_to_json(events), content_type='application/json')

'''the create appointment view creates an appointment for the calendar dependent on the type of user'''
class CreateAppointmentView(FormMixin, generic.FormView):
    template_name = 'main/makeAppointment.html'

    def get_form_class(self):
        user = self.request.user
        if hasattr(user, 'patient'):
            return PatientAppointment
        elif hasattr(user, 'doctor'):
            return DoctorAppointment
        elif hasattr(user, 'nurse'):
            return NurseAppointment

    def get_success_url(self):
        return reverse_lazy('fullcalendar:index')

    def get_initial(self):
        user = self.request.user

        if hasattr(user, 'patient'):
            initial = {'hospital': user.patient.preferred_hospital,
                       'start_date': timezone.now().date(),
                       'start_time': timezone.now().time()}
        else:
            initial = {'start_date': timezone.now().date(), }
        return initial

    def form_valid(self, form):
        user = self.request.user
        if hasattr(user, 'patient'):
            event = CalendarEvent.objects.create(patient=user.patient,
                                                 doctor=form.cleaned_data['doctor'],
                                                 hospital=form.cleaned_data['hospital'],
                                                 title=form.cleaned_data['description'],
                                                 start=datetime.combine(form.cleaned_data['start_date'],
                                                                        form.cleaned_data['start_time']),
                                                 end=datetime.combine(form.cleaned_data['start_date'],
                                                                      form.cleaned_data['start_time'])+ timedelta(hours=1))
            message = Message.objects.create()
            message.sender = user
            message.recipient = event.doctor.user
            message.subject = 'New Appointment'
            message.body = event.patient.get_name() + " has made an appointment, view and confirm from your calendar"
            message.moderation_status = 'a'

            event.save()
            message.save()
        elif hasattr(user, 'doctor'):
            event = CalendarEvent.objects.create(patient=form.cleaned_data['patient'],
                                                 doctor=user.doctor,
                                                 hospital=form.cleaned_data['hospital'],
                                                 title=form.cleaned_data['description'],
                                                 start=datetime.combine(form.cleaned_data['start_date'],
                                                                        form.cleaned_data['start_time']),
                                                 end=datetime.combine(form.cleaned_data['start_date'],
                                                                      form.cleaned_data['start_time'])+ timedelta(hours=1))
            message = Message.objects.create()
            message.sender = user
            message.recipient = event.patient.user
            message.subject = 'New Appointment'
            message.body = event.doctor.get_name() + " has made an appointment for you, view from your calendar"
            message.moderation_status = 'a'

            event.save()
            message.save()
        elif hasattr(user, 'nurse'):
            event = CalendarEvent.objects.create(patient=user.cleaned_data['patient'],
                                                 doctor=form.cleaned_data['doctor'],
                                                 hospital=form.cleaned_data['hospital'],
                                                 title=form.cleaned_data['description'],
                                                 start=datetime.combine(form.cleaned_data['start_date'],
                                                                        form.cleaned_data['start_time']),
                                                 end=datetime.combine(form.cleaned_data['start_date'],
                                                                      form.cleaned_data['start_time'])+ timedelta(hours=1))

            event.save()
        customLog.add_log("%s created an appointment" % user.username, 'APPOINC')
        return super(CreateAppointmentView, self).form_valid(form)

class AppointmentView(FormMixin, generic.DetailView):

    model = CalendarEvent

    template_name = 'fullcalendar/event_detail.html'

    def dispatch(self, request, *args, **kwargs):
        self.canverify = hasattr(request.user, 'doctor')
        self.event = self.get_event()
        return super(AppointmentView, self).dispatch(request, *args, **kwargs)

    def get_event(self):
        return CalendarEvent.objects.get(pk=self.kwargs['pk'])


class AppointmentVerify(generic.FormView):
    template_name = 'fullcalendar/event_verify.html'
    form_class = BooleanForm

    def dispatch(self, request, *args, **kwargs):
        self.event = self.get_event()
        return super(AppointmentVerify, self).dispatch(request, *args, **kwargs)

    def get_success_url(self):
        return reverse('fullcalendar:detail', kwargs={'pk': self.kwargs['pk']})

    def get_event(self):
        return CalendarEvent.objects.get(pk=self.kwargs['pk'])

    def form_valid(self, form):
        self.event.verified = form.cleaned_data['confirm']
        self.event.save()
        return super(AppointmentVerify, self).form_valid(form)


'''view for displaying an appointment, retrieves the correct type of information based on user type
and allows for modification of appointment'''
class AppointmentEdit(FormMixin, generic.FormView):

    template_name = 'fullcalendar/event_edit.html'

    def dispatch(self, request, *args, **kwargs):
        self.event = self.get_event()
        return super(AppointmentEdit, self).dispatch(request, *args, **kwargs)

    def get_event(self):
        return CalendarEvent.objects.get(pk=self.kwargs['pk'])

    def get_form_class(self):
        user = self.request.user
        if hasattr(user, 'patient'):
            return PatientAppointment
        elif hasattr(user, 'doctor'):
            return DoctorAppointment
        elif hasattr(user, 'nurse'):
            return NurseAppointment

    def get_success_url(self):
        return reverse('fullcalendar:detail', kwargs={'pk': self.kwargs['pk']})

    def get_initial(self):
        event = self.get_event()
        user = self.request.user
        if hasattr(user, 'patient'):
            initial = {
                'hospital': event.hospital,
                'patient': event.patient,
                'doctor': event.doctor,
                'start_date': event.start.date(),
                'start_time': event.start.time(),
                'description': event.title
            }
            if user.patient != event.patient:
                raise PermissionDenied
        elif hasattr(user, 'doctor'):
            initial = {
                'hospital': event.hospital,
                'patient': event.patient,
                'doctor': event.doctor,
                'start_date': event.start.date(),
                'start_time': event.start.time(),
                'description': event.title,

HealthNet/healthnet_BKZ/HealthNet/fullcalendar/templates/fullcalendar/base.html
{% load fullcalendar_tags %}
{% load staticfiles %}
{% load main_extras %}
<!DOCTYPE HTML>
<!--
	Minimaxing by HTML5 UP
	html5up.net | @ajlkn
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
<html>
	<head>
		<title>HealthNet | Calendar</title>
		<link rel="shortcut icon" href="{% static 'main/images/bkz_io.png' %}"/>
		<meta charset="utf-8" />
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<meta name="description" content="">
		<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
		<link href="{% static 'css/bootstrap-theme.min.css' %}" rel="stylesheet">
		<script src="https://use.fontawesome.com/d4ff336425.js"></script>
		<link rel="stylesheet" href="{% static 'css/main.css' %}" >

		<!-- Place favicon.ico and apple-touch-icon.png in the root directory -->
        {% fullcalendar_css %}        
        {% fullcalendar_print_css %}        
        {% fullcalendar_jquery %}
        {% fullcalendar_jquery_ui %}
        {% fullcalendar_javascript %}
        
        {% calendar_init calendar_config_options %}
	</head>
	<body>
		<div id="page-wrapper">
			{% include 'main/navbar.html' %}
			<div class="container">
				<a class="button_temp pull-left" href = "{% url 'fullcalendar:makeAppointment' %}" role="button" style="margin:5px;"><i class="fa fa-calendar-plus-o"></i>&nbsp;&nbsp;Make an Appointment</a>
    			<div class="row" style="margin: 15px; width:100%;">
      				<div class="col-sm-12">
        				{% block content %}

        				{% endblock %}
      				</div>
    			</div>
    					
    		<div class="row">
						<div class="12u">

							<div id="copyright">
								&copy; Untitled. All rights reserved. | Design: <a href="http://html5up.net">HTML5 UP</a>
							</div>

						</div>
					</div>
    		</div>
		</div>

		<!-- Scripts -->
			<script src="assets/js/jquery.min.js"></script>
			<script src="assets/js/skel.min.js"></script>
			<script src="assets/js/skel-viewport.min.js"></script>
			<script src="assets/js/util.js"></script>
			<!--[if lte IE 8]><script src="assets/js/ie/respond.min.js"></script><![endif]-->
			<script src="assets/js/main.js"></script>

	</body>
</html>

HealthNet/healthnet_BKZ/HealthNet/fullcalendar/templates/fullcalendar/calendar.html
<div id="calendar" style="background-color: white;"></div>

HealthNet/healthnet_BKZ/HealthNet/fullcalendar/templates/fullcalendar/calendar_init.html
<script type="text/javascript">
    $(document).ready(function() {
        // page is now ready, initialize the calendar...
        $('#calendar').fullCalendar({{ calendar_config_options }});
    });
</script>

HealthNet/healthnet_BKZ/HealthNet/fullcalendar/templates/fullcalendar/event_confirm_delete.html
{% load staticfiles %}
<!DOCTYPE HTML>
<!--
	Minimaxing by HTML5 UP
	html5up.net | @ajlkn
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
<html>
	<head>
		<title>HealthNet - </title>
		<link rel="shortcut icon" href="{% static 'main/images/bkz_io.png' %}"/>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<!--[if lte IE 8]><script src="assets/js/ie/html5shiv.js"></script><![endif]-->
		<!--[if lte IE 9]><link rel="stylesheet" href="assets/css/ie9.css" /><![endif]-->
		<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
		<link href="{% static 'css/bootstrap-theme.min.css' %}" rel="stylesheet">
		<script src="https://use.fontawesome.com/d4ff336425.js"></script>
		<link rel="stylesheet" href="{% static 'css/main.css' %}" >
		<link rel="stylesheet" href="{% static 'css/profile.css' %}" >
	</head>
	<body>
		<div id="page-wrapper">
			<div id="header-wrapper">
				<div class="container_temp">
					<div class="row_temp">
						<div class="12u">
							<header id="header">
								<h1><a href="#" id="logo">HealthNet</a></h1>
							</header>

						</div>
					</div>
				</div>
			</div>
			<div class="main">
				<div class="row" style="margin:20px;"></div>
				<form action="" method="post">{% csrf_token %}
				    <p class="well">Are you sure you want to delete "{{ object }}"?</p>
				    <input class="button_temp pull-right" type="submit" value="Confirm" />
			        <a href="{% url 'fullcalendar:detail' pk=view.kwargs.pk %}" class="button_temp pull-right" />Back</a>
				</form>
				<div class="row" style="margin:20px;"></div>
			</div>
			<div class="row">
				<div class="12u">
					<div id="copyright">
						&copy; Untitled. All rights reserved. | Design: <a href="http://html5up.net">HTML5 UP</a>
					</div>
				</div>
			</div>


			<!-- Scripts -->
			<script src="assets/js/jquery.min.js"></script>
			<script src="assets/js/skel.min.js"></script>
			<script src="assets/js/skel-viewport.min.js"></script>
			<script src="assets/js/util.js"></script>
			<!--[if lte IE 8]><script src="assets/js/ie/respond.min.js"></script><![endif]-->
			<script src="assets/js/main.js"></script>

	</body>
</html>

HealthNet/healthnet_BKZ/HealthNet/fullcalendar/templates/fullcalendar/event_detail.html
{% extends 'main/base_nav.html' %}
{% load staticfiles %}
{% load main_extras %}

{% block page-title %} Appointment Details - {{object.title}} {% endblock %}

{% block head %}
		<link rel="stylesheet" href="{% static 'css/profile.css' %}" >
{% endblock %}

{% block main %}
		<div id="page-wrapper">
			<div id="header-wrapper">
				<div class="container_temp">
					<div class="row_temp">
						<div class="12u">
							<header id="header">
								<h1><a href="#" id="logo">HealthNet</a></h1>
							</header>

						</div>
					</div>
				</div>
			</div>
			<div class="main">
				<div class="row" style="margin:20px;"></div>
				{% if form.errors %}
			        <!-- Error messaging -->
			            <div id="errors">
			                <div class="inner" >
			                    <p>There were some errors in the information you entered. Please correct the following:</p>
			                    {{ form.non_field_errors }}
			                    <ul>
			                        {% for field in form %}
			                            {% if field.errors %}<li>{{ field.label }}: {{ field.errors|striptags }}</li>{% endif %}
			                        {% endfor %}
			                    </ul>
			                </div>
			            </div>
				<!-- /Error messaging -->
			 {% endif %}

			    <form method = 'post'>
			        {% csrf_token %}
			        <div class="container">
							<div class="row">
								<h2>
									Appointment Details - {{object.title}}
								</h2>
								<h3>
									Hospital: {{ object.hospital }}
								</h3>
							</div>
							<div class="row">
								<h3>
									Doctor: {{ object.doctor.get_name }}
								</h3>
							</div>
							<div class="row">
								<h3>
									Start Date: {{ object.start.date }}
								</h3>
							</div>
							<div class="row">
								<h3>
									Start Time: {{ object.start.time }}
								</h3>
							</div>
							<div class="row">
								<h3>
									End Date{{ object.end.date }}
								</h3>
							</div>
							<div class="row">
								<h3>
									End Time{{ object.end.time }}
								</h3>
							</div>
							<div class="row">
								<h3>
									Patient: {{ object.patient.get_name }}
								</h3>
							</div>
							<div class="row">
								<h3>
									{% if object.verified %} Verified by Doctor. {% endif %}
								</h3>
							</div>
			        </div>

			        <a href="{% url 'fullcalendar:index' %}" class="button_temp pull-left" />Back</a>
			        {% if not object.verified %}{% if view.canverify %}<a href="{% url 'fullcalendar:verifyAppointment' pk=view.kwargs.pk %}" class="button_temp pull-right" />Verify</a>{% endif %}{% endif %}
			        <a href="{% url 'fullcalendar:editAppointment' pk=view.kwargs.pk %}" class="button_temp pull-right" />Edit</a>
			        <a href="{% url 'fullcalendar:deleteAppointment' view.kwargs.pk %}" class="button_temp_red pull-right" />Delete</a>

			    </form>

				<div class="row" style="margin:20px;"></div>
			</div>
			<div class="row">
				<div class="12u">
					<div id="copyright">
						&copy; Untitled. All rights reserved. | Design: <a href="http://html5up.net">HTML5 UP</a>
					</div>
				</div>
			</div>
{% endblock main %}

HealthNet/healthnet_BKZ/HealthNet/fullcalendar/templates/fullcalendar/event_edit.html
{% extends 'main/base_nav.html' %}
{% load staticfiles %}
{% load main_extras %}

{% block page-title %} Edit Appointment {% endblock %}

{% block head %}
		<link rel="stylesheet" href="{% static 'css/profile.css' %}" >
{% endblock %}

{% block main %}
		<div id="page-wrapper">
			<div id="header-wrapper">
				<div class="container_temp">
					<div class="row_temp">
						<div class="12u">
							<header id="header">
								<h1><a href="#" id="logo">HealthNet</a></h1>
							</header>

						</div>
					</div>
				</div>
			</div>
			<div class="main">
				<div class="row" style="margin:20px;"></div>
				<div class="col-sm-3"></div>
				<div class="col-sm-6">
				{% if form.errors %}
			        <!-- Error messaging -->
			            <div id="errors">
			                <div class="inner" >
			                    <p>There were some errors in the information you entered. Please correct the following:</p>
			                    {{ form.non_field_errors }}
			                    <ul>
			                        {% for field in form %}
			                            {% if field.errors %}<li>{{ field.label }}: {{ field.errors|striptags }}</li>{% endif %}
			                        {% endfor %}
			                    </ul>
			                </div>
			            </div>
				<!-- /Error messaging -->
			 	{% endif %}

			    <form method = 'post'>
			        {% csrf_token %}
			        <div class="container">
							<div class="row">
								<div>
									{{ form.hospital }}
								</div>
							</div>
							<div class="row">
								<div>
									{{ form.doctor }}
								</div>
							</div>
							<div class="row">
								<div>
									{{ form.start_date }}
								</div>
							</div>
							<div class="row">
								<div>
									{{ form.start_time }}
								</div>
							</div>
							<div class="row">
								<div>
									{{ form.end_date }}
								</div>
							</div>
							<div class="row">
								<div>
									{{ form.end_time }}
								</div>
							</div>
			                <div class="row">
								<div>
									{{ form.description }}
								</div>
							</div>
							<div class="row">
								<div>
									{{ form.patient }}
								</div>
							</div>
							<div class="row">
								<div>
									{{form.verified.label_tag}}
									{{ form.verified }}

								</div>
							</div>
			        </div>

			        <a href="{% url 'fullcalendar:detail' pk=view.kwargs.pk %}" class="button_temp pull-left" />Back</a>
			        <input class="button_temp pull-right" role="button" type="submit" value="Submit Edits" />

			    </form>
			    </div>
			    <div class="col-sm-3"></div>
				<div class="row" style="margin:20px;"></div>
			</div>
			<div class="row">
				<div class="12u">
					<div id="copyright">
						&copy; Untitled. All rights reserved. | Design: <a href="http://html5up.net">HTML5 UP</a>
					</div>
				</div>
			</div>
{% endblock main %}

HealthNet/healthnet_BKZ/HealthNet/fullcalendar/templates/fullcalendar/event_verify.html
{% extends 'main/base_nav.html' %}
{% load staticfiles %}
{% load main_extras %}

{% block page-title %} Confirm Appointment {% endblock page-title %}

{% block head %}
		<link rel="stylesheet" href="{% static 'css/profile.css' %}" >
{% endblock head %}

{% block main %}
		<div id="page-wrapper">
			<div id="header-wrapper">
				<div class="container_temp">
					<div class="row_temp">
						<div class="12u">
							<header id="header">
								<h1><a href="#" id="logo">HealthNet</a></h1>
							</header>

						</div>
					</div>
				</div>
			</div>
			<div class="main">
				<div class="row" style="margin:20px;"></div>
				<form method="post">
                    {% csrf_token %}
				    <h3>Are you sure you want to verify the following appointment?</h3>
                        Patient: {{ view.event.patient.get_name }}<br>
                        Appointment: {{ view.event.title }}<br>
                        Location: {{ view.event.hospital }}<br>
                        Time: {{ view.event.start.time }} <br>
                        Date: {{ view.event.start.date }}<br>
                        Doctor: {{ view.event.doctor.get_name }}<br><br>
                        Before verifying, please confirm that this appointment does no conflict with any pre-existing appointments.  <br>
                        Confirm? {{ form.confirm }} <br>
			        <a class="button_temp pull-left" href="{% url 'fullcalendar:detail' pk=view.event.pk%}" role="button" style="margin-right: 5px;">Back</a>
			        <input class="button_temp_red pull-left" type="submit" name="edit" value="Verify"/>
				</form>
				<div class="row" style="margin:20px;"></div>
			</div>
			<div class="row">
				<div class="12u">
					<div id="copyright">
						&copy; Untitled. All rights reserved. | Design: <a href="http://html5up.net">HTML5 UP</a>
					</div>
				</div>
			</div>
{% endblock main %}

HealthNet/healthnet_BKZ/HealthNet/fullcalendar/templates/fullcalendar/index.html
{% extends "fullcalendar/base.html" %}

{% load fullcalendar_tags %}

{% load staticfiles %}

{% block content %}

	{{ block.super }}
	{% calendar %}

{% endblock content %}
